spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/ride_booking
spring.datasource.username=root
spring.datasource.password=Mansi@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# NEW: Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mansisahu3512@gmail.com
spring.mail.password=MaNsI@2005
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
